name: neom_home
description: Home for Cyberneom.
version: 1.1.1
homepage: https://github.com/Cyberneom/neom_home
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  neom_commons:
    git:
      url: https://github.com/Cyberneom/neom_commons.git
  neom_events:
    git:
      url: https://github.com/Cyberneom/neom_events.git
  neom_inbox:
    git:
      url: https://github.com/Cyberneom/neom_inbox.git
  neom_itemlists:
    git:
      url: https://github.com/Cyberneom/neom_itemlists.git
  neom_music_player:
    git:
      url: https://github.com/Cyberneom/neom_music_player.git
  neom_posts:
    git:
      url: https://github.com/Cyberneom/neom_posts.git
  neom_profile:
    git:
      url: https://github.com/Cyberneom/neom_profile.git
  neom_timeline:
    git:
      url: https://github.com/Cyberneom/neom_timeline.git
  neom_booking:
    git:
      url: https://github.com/emmanuel-montoya/neom_booking.git
  neom_commerce:
    git:
      url: https://github.com/emmanuel-montoya/neom_commerce.git
  neom_jobs:
    git:
      url: https://github.com/emmanuel-montoya/neom_jobs.git
#  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  neom_booking:
    path: ../neom_booking
  neom_commerce:
    path: ../neom_commerce
  neom_commons:
    path: ../neom_commons
  neom_events:
    path: ../neom_events
  neom_inbox:
    path: ../neom_inbox
  neom_jobs:
    path: ../neom_jobs
  neom_itemlists:
    path: ../neom_itemlists
  neom_music_player:
    path: ../neom_music_player
  neom_posts:
    path: ../neom_posts
  neom_profile:
    path: ../neom_profile
  neom_timeline:
    path: ../neom_timeline
  uuid: 4.1.0
  logger: 2.0.2+1
#  http: 1.1.0
#  google_api_headers: 2.0.3

# The following section is specific to Flutter packages.
flutter:
